### ISSUE TITLE
add prettier

### ISSUE THREAD

**Issue by sibelius** [lXSPandora/MapApplication-React-Native#1]

**Comment by rodrigooler** [comment]
Prettier is an opinionated code formatter. 

https://prettier.github.io/prettier/
https://github.com/prettier/prettier

**Comment by sibelius** [comment]
https://user-images.githubusercontent.com/1283200/27655291-3f31490e-5c1b-11e7-9dae-10997f8ee008.png

**Comment by lXSPandora** [comment]
prettier added!!
